#!/usr/bin/env node
// Syncs the collection lists in index.html with what actually exists in Postman.
//
// The portal is a *curated* subset of the team's public workspaces, and its display
// names, icons, categories and descriptions are hand-written. So this script only
// ever owns one field: `collections`. Everything else is preserved verbatim, nothing
// is auto-added, and nothing is auto-deleted — surprises get reported instead.
//
//   POSTMAN_API_KEY=... node scripts/sync.mjs [--dry-run]

import { readFileSync, writeFileSync, appendFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const API = 'https://api.getpostman.com';
const TEAM = 'opencollections';
const USER_ID = 6045849;

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const INDEX = join(ROOT, 'index.html');

const DRY_RUN = process.argv.includes('--dry-run');
const KEY = process.env.POSTMAN_API_KEY;

const report = [];
function say(line = '') {
  report.push(line);
  console.log(line);
}

// --- Postman API ------------------------------------------------------------

async function api(path) {
  const res = await fetch(API + path, { headers: { 'X-Api-Key': KEY } });
  if (!res.ok) {
    throw new Error(`GET ${path} → ${res.status} ${res.statusText}\n${await res.text()}`);
  }
  return res.json();
}

async function publicWorkspaces() {
  const all = [];
  let cursor = '';
  do {
    const qs = `?createdBy=${USER_ID}&limit=100${cursor ? `&cursor=${encodeURIComponent(cursor)}` : ''}`;
    const page = await api(`/workspaces${qs}`);
    all.push(...(page.workspaces ?? []));
    cursor = page.meta?.nextCursor ?? '';
  } while (cursor);
  return all.filter(w => w.visibility === 'public');
}

async function collectionsIn(workspaceId) {
  const all = [];
  for (let offset = 0; ; offset += 100) {
    const page = await api(`/collections?workspace=${workspaceId}&limit=100&offset=${offset}`);
    const batch = page.collections ?? [];
    all.push(...batch);
    if (batch.length < 100) break;
  }
  // A non-public collection renders a "Run in Postman" button that 404s for visitors.
  return all
    .filter(c => c.isPublic)
    .map(c => ({ name: c.name, uid: c.uid }))
    .sort((a, b) => a.name.localeCompare(b.name, 'en', { numeric: true }));
}

// --- index.html read/write --------------------------------------------------

const START = '// WORKSPACES:START';
const END = '// WORKSPACES:END';

function readCuration(html) {
  const from = html.indexOf(START);
  const to = html.indexOf(END);
  if (from === -1 || to === -1) {
    throw new Error(`Could not find ${START} / ${END} markers in index.html`);
  }
  const block = html.slice(html.indexOf('\n', from) + 1, to);
  const literal = block.slice(block.indexOf('['), block.lastIndexOf(']') + 1);
  // Our own file, no imports — new Function beats hand-rolling a JS parser, and
  // JSON.parse chokes on unquoted keys, single quotes and trailing commas.
  return new Function(`return ${literal}`)();
}

function quote(s) {
  if (s.includes('</script')) throw new Error(`Refusing to emit "</script" inside a script tag: ${s}`);
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function emit(workspaces) {
  const entry = ws => {
    const cols = ws.collections.length === 0
      ? '    collections: [],'
      : [
          '    collections: [',
          ...ws.collections.map(c => `      { name: ${quote(c.name)}, uid: ${quote(c.uid)} },`),
          '    ],',
        ].join('\n');
    return [
      '  {',
      `    id: ${quote(ws.id)},`,
      `    name: ${quote(ws.name)},`,
      `    icon: ${quote(ws.icon)},`,
      `    category: ${quote(ws.category)},`,
      `    description: ${quote(ws.description)},`,
      cols,
      '  },',
    ].join('\n');
  };
  return [
    '// Generated by scripts/sync.mjs — `collections` lists come from the Postman API.',
    '// name, icon, category and description are hand-maintained; the script never touches them.',
    'const WORKSPACES = [',
    ...workspaces.map(entry),
    '];',
  ].join('\n');
}

function splice(html, body) {
  const from = html.indexOf(START);
  const to = html.indexOf(END);
  const head = html.slice(0, html.indexOf('\n', from) + 1);
  return head + body + '\n' + html.slice(to);
}

// The page recomputes every counter in JS on load, but these literals are what
// shows before the script runs — keep them honest.
function setText(html, id, value) {
  const re = new RegExp(`(id="${id}"[^>]*>)[^<]*`);
  if (!re.test(html)) {
    say(`  ! no element with id="${id}" — counter not updated`);
    return html;
  }
  return html.replace(re, `$1${value}`);
}

function syncCounters(html, workspaces) {
  const total = workspaces.reduce((n, w) => n + w.collections.length, 0);
  html = setText(html, 'stat-workspaces', workspaces.length);
  html = setText(html, 'stat-collections', total);
  html = setText(html, 'count-all', workspaces.length);
  html = setText(html, 'visible-count', workspaces.length);
  for (const cat of new Set(workspaces.map(w => w.category))) {
    html = setText(html, `count-${cat}`, workspaces.filter(w => w.category === cat).length);
  }
  return html;
}

// --- link check -------------------------------------------------------------

function slug(name) {
  return name.toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-');
}

const workspaceUrl = name => `https://www.postman.com/${TEAM}/${slug(name)}`;

async function checkLinks(workspaces) {
  say('');
  say('## Link check');
  say('');
  say('The public workspace URL is derived from the *display* name, so a rename in');
  say('Postman can break it silently. Status codes only — postman.com may soft-404.');
  say('');
  for (const ws of workspaces) {
    const url = workspaceUrl(ws.name);
    let status;
    try {
      status = (await fetch(url, { redirect: 'follow' })).status;
    } catch (err) {
      status = `error: ${err.message}`;
    }
    say(`- ${status === 200 ? '200' : `**${status}**`} — ${ws.name} → ${url}`);
  }
}

// --- main -------------------------------------------------------------------

function diffCollections(before, after) {
  const key = c => c.uid;
  const b = new Map(before.map(c => [key(c), c]));
  const a = new Map(after.map(c => [key(c), c]));
  return {
    added: after.filter(c => !b.has(key(c))),
    removed: before.filter(c => !a.has(key(c))),
    renamed: after
      .filter(c => b.has(key(c)) && b.get(key(c)).name !== c.name)
      .map(c => ({ from: b.get(key(c)).name, to: c.name })),
  };
}

async function main() {
  if (!KEY) {
    console.error('POSTMAN_API_KEY is not set.');
    process.exit(1);
  }

  const original = readFileSync(INDEX, 'utf8');
  const curated = readCuration(original);
  const live = await publicWorkspaces();
  const liveById = new Map(live.map(w => [w.id, w]));

  say(`# Postman sync${DRY_RUN ? ' (dry run)' : ''}`);
  say('');
  say(`${curated.length} curated workspaces · ${live.length} public in Postman`);
  say('');
  say('## Collection changes');
  say('');

  const merged = [];
  let touched = 0;
  const proseWarnings = [];

  for (const ws of curated) {
    if (!liveById.has(ws.id)) {
      say(`- **${ws.name}** — no longer public (or deleted) in Postman. Left untouched; remove it by hand if that was intentional.`);
      merged.push(ws);
      continue;
    }
    const after = await collectionsIn(ws.id);
    const { added, removed, renamed } = diffCollections(ws.collections, after);
    if (added.length || removed.length || renamed.length) {
      touched++;
      say(`- **${ws.name}**`);
      for (const c of added) say(`  - added: ${c.name}`);
      for (const c of removed) say(`  - removed: ${c.name}`);
      for (const r of renamed) say(`  - renamed: ${r.from} → ${r.to}`);
      if (added.length || removed.length) proseWarnings.push(ws.name);
    }
    merged.push({ ...ws, collections: after });
  }

  if (touched === 0) say('- none');

  const untracked = live.filter(w => !curated.some(c => c.id === w.id));
  say('');
  say('## Public in Postman, not in the portal');
  say('');
  if (untracked.length === 0) {
    say('- none');
  } else {
    say('Not added automatically — paste an entry with an icon and category if you want it listed.');
    say('');
    for (const w of untracked) {
      say(`- **${w.name}** — \`${w.id}\``);
      if (w.about) say(`  > ${w.about.replace(/\s+/g, ' ').trim()}`);
    }
  }

  if (proseWarnings.length) {
    say('');
    say('## Descriptions worth re-reading');
    say('');
    say('Collection counts moved in these workspaces, and descriptions are hand-written');
    say('(this script never edits them):');
    say('');
    for (const name of proseWarnings) say(`- ${name}`);
  }

  let updated = splice(original, emit(merged));
  updated = syncCounters(updated, merged);

  say('');
  if (updated === original) {
    say('## Result');
    say('');
    say('index.html already up to date — nothing written.');
  } else if (DRY_RUN) {
    say('## Result');
    say('');
    say('index.html would change (dry run — nothing written).');
  } else {
    writeFileSync(INDEX, updated);
    say('## Result');
    say('');
    say('index.html updated.');
  }

  await checkLinks(merged);

  if (process.env.GITHUB_STEP_SUMMARY) {
    appendFileSync(process.env.GITHUB_STEP_SUMMARY, report.join('\n') + '\n');
  }
}

main().catch(err => {
  console.error(err.message);
  process.exit(1);
});
